### ISSUE TITLE
New pre-built binaries

### ISSUE THREAD

**Issue by christophetd** [projectdiscovery/cloudlist#14]
Hello,

Would it be possible to have a new release with new built-in binaries? Those on the release page are from Dec 2020 and it seems are missing some patches / improvements

Thank you!

**Comment by ehsandeep** [comment]
Hi @christophetd, 

Those recent changes were mostly related to maintenance - https://github.com/projectdiscovery/cloudlist/compare/dev, soon we will continue to work on this project and add new providers along with pushing new release.

Thanks for the reminder.
